version: '3.1'
services:
  beemstream_cms:
    image: beemstream-cms
    volumes:
      - public:/app/public
    environment:
      SESSION_SECRET_FILE: /run/secrets/cms_session_secret_two
      DATABASE_URL_FILE: /run/secrets/cms_database_url
    secrets:
      - cms_session_secret
      - cms_database_url
    ports:
      - "80:3000"

secrets:
  cms_session_secret:
    external: true
  cms_database_url:
    external: true

volumes:
  public:
    external: true
